---
- name: Configure Team Accounts
  tower_team:
    name: "{{ team.name }}"
    description: "{{ team.description | default(default_description) }}"
    organization: "{{ team.organization | default(default_organization) }}"
    state: "{{ team.state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ teams }}"
  loop_control:
    loop_var: team

- name: Configure and Tag Project to Team's account with permission privilege
  tower_role:
    project: "{{ team.project | default(default_project) }}"
    team: "{{ team.name }}"
    role: "{{ team.project_role }}"
    tower_verify_ssl: "{{ team.tower_verify_ssl | default(omit) }}"
    state: "{{ team.state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ teams }}"
  loop_control:
    loop_var: team

- name: Configure and Tag Inventory to Team's account with permission privilege
  tower_role:
    inventory: "{{ team.inventory | default(default_inventory) }}"
    team: "{{ team.name }}"
    role: "{{ team.inventory_role }}"
    tower_verify_ssl: "{{ team.tower_verify_ssl | default(omit) }}"
    state: "{{ team.state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ teams }}"
  loop_control:
    loop_var: team

- name: Configure and Tag User to Team's account with permission privilege
  tower_role:
    user: "{{ team.user }}"
    target_team: "{{ team.name }}"
    role: "{{ team.user_role }}"
    tower_verify_ssl: "{{ team.tower_verify_ssl | default(omit) }}"
    state: "{{ team.state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ teams }}"
  loop_control:
    loop_var: team
  when: team.user

- name: Configure and Tag Project to Default Team's account with permission privilege
  tower_role:
    project: "{{ default_project }}"
    team: "{{ default_team.name }}"
    role: "{{ default_team.permission }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ default_teams }}"
  loop_control:
    loop_var: default_team
