---
- include_vars:
    file: ../inventory.yaml
    name: inventory_new

- name: Parsing Inventory
  set_fact:
    parse_inventory: "{{ parse_inventory +  [item] }}"
  loop: "{{ inventory_new | dict2items }}"

- name: Passing values to Inventory items
  set_fact:
    inventory_name: "{{ item.value.name | default('Network Nodes') }}"
    inventory_description: "{{ item.value.description | default('This is Default Inventory Network Nodes') }}"
    inventory_organization: "{{ item.value.organization | default('Default') }}"
    inventory_variables: "{{ item.value.variables }}"
    hosts: "{{ item.value.hosts }}"
  loop: "{{ parse_inventory }}"

- set_fact:
    host_names: "{{ host_names + [item.value] }}"
  loop: "{{ hosts | dict2items }}"
  when: item.value != "vars"

- import_role:
    name: tower_inventory
    tasks_from: configure_inventory
  vars:
    parse_inventory: []
    group_names: []
    host_names: []

    inventory:
    - name: "{{ inventory_name }}"
      description: "{{ inventory_description }}"
      organization: "{{ inventory_organization }}"
      variables: "{{ inventory_variables }}"
      host_names: "{{ host_names }}"
      hosts: "{{ hosts }}"
