---
# tasks file for ansible_tower
#
- block:
    - name: initialize role
      include_tasks: "{{ role_path }}/includes/init.yaml"

    - name: set ansible_tower_catalog
      set_fact:
        ansible_tower_catalog: "{{ ansible_tower_enable_catalogs.split(',') }}"

    - debug: var=ansible_tower_catalog
    - debug: var=ansible_tower_custom_catalog_path

    - name: install catalog
      include_tasks: "{{ role_path }}/includes/loader.yaml"
      loop: "{{ ansible_tower_enable_catalogs.split(',') }}"
      loop_control:
        loop_var: ansible_tower_catalog_item
  tags:
    - always
