---
# tasks file for ansible_tower
#
- name: always run block
  block:
    - name: initialize role
      include_tasks: "{{ role_path }}/includes/init.yaml"

    - name: get catalog artifacts file list
      find:
        path: "{{ ansible_tower_catalog_path }}"
      register: ansible_tower_resources
  tags:
    - always

- block:
    - name: get catalog artifacts
      set_fact:
        ansible_tower_credentials: "{{ lookup('file', ansible_tower_catalog_path ~ 'credentials.yaml') | from_yaml }}"

    - name: configure credentials
      include_tasks: "{{ role_path }}/includes/credential.yaml"
      loop: "{{ ansible_tower_credentials }}"
  when:
    - "'credentials' in ansible_tower_resources"
  tags:
    - credentials

- name: configure teams
  include_tasks: "{{ role_path }}/includes/team.yaml"
  loop: "{{ ansible_tower.teams }}"
  when:
    - ansible_tower.teams is defined
  tags:
    - teams

- name: configure user accounts
  include_tasks: "{{ role_path }}/includes/user.yaml"
  loop: "{{ ansible_tower.users }}"
  when:
    - ansible_tower.users is defined
  tags:
    - users

- name: configure inventories
  include_tasks: "{{ role_path }}/includes/inventory.yaml"
  loop: "{{ ansible_tower.inventories }}"
  when:
    - ansible_tower.inventories is defined
  tags:
    - inventory

- name: configure projects
  include_tasks: "{{ role_path }}/includes/project.yaml"
  loop: "{{ ansible_tower.projects }}"
  when:
    - ansible_tower.projects is defined
  tags:
    - projects

- name: configure job_templates
  include_tasks: "{{ role_path }}/includes/job_template.yaml"
  loop: "{{ ansible_tower.job_templates }}"
  when:
    - ansible_tower.job_templates is defined
  tags:
    - job_templates

- name: configure projects
  include_tasks: "{{ role_path }}/includes/project.yaml"
  loop: "{{ ansible_tower.projects }}"
  when:
    - ansible_tower.projects is defined
    - tower_state == 'absent'
  tags:
    - project_clean
