---
- name: Create Inventory
  tower_inventory:
    name: "{{ item.name | default(default_inventory) }}"
    organization: "{{ item.organization | default(default_organization) }}"
    description: "{{ item.description | default(default_description) }}"
    variables: "{{ item.variables }}"
    state: "{{ item.state | default(omit) }}"
   #tower_config_file: tower_cli.cfg
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ inventory }}"
  when: item.name is defined

- name: Create Group
  tower_group:
    name: "{{ host }}"
    inventory: "{{ inventory[0].name | default(default_inventory) }}"
    description: "{{ inventory[0].hosts[host].description | default(default_group_description) }}"
    variables: "{{ inventory[0].hosts[host].vars }}"
    state: "{{ inventory[0].hosts[host].state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ inventory[0].hosts.keys() }}"
  loop_control:
    loop_var: host
  when:
  - inventory[0].name is defined
  - host is defined

- name: Create Host
  tower_host:
    name: "{{ hostname }}"
    inventory: "{{ inventory[0].name | default(default_inventory) }}"
    description: "{{ inventory[0].host_names[0][hostname].description | default(default_host_description) }}"
    variables: "ansible_host: {{ inventory[0].host_names[0][hostname].ansible_host }}"
    state: "{{ inventory[0].host_names[0][hostname].state | default(omit) }}"
    tower_host: "{{ tower_vault_host }}"
    tower_password: "{{ tower_vault_password }}"
    tower_username: "{{ tower_vault_username }}"
  loop: "{{ inventory[0].host_names[0].keys() }}"
  loop_control:
    loop_var: hostname
  when:
  - hostname != "vars"
  - inventory[0].host_names[0][hostname].ansible_host is defined
