---
- name: handle user block
  block:
    - name: validate item.name is defined
      fail:
        msg: "missing required value for user: item.name"
      when: item.name is undefined

    - name: validate item.email is defined
      fail:
        msg: "missing required value for user: item.email"
      when: item.email is undefined

    - name: configure user accounts
      tower_user:
        username: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
        email: "{{ item.email }}"

        first_name: "{{ item.first_name | default(omit) }}"
        last_name: "{{ item.last_name | default(omit) }}"

        superuser: "{{ item.user_privilege | default(omit) }}"
        auditor: "{{ item.auditor | default(omit) }}"

        state: "{{ item.state | default(omit) }}"

        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl | default(omit) }}"

    - name: add user account to team
      tower_role:
        user: "{{ item.name }}"
        target_team: "{{ team }}"

        role: "{{ item.role | default('member') }}"

        state: "{{ item.state | default(omit) }}"

        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl | default(omit) }}"

      loop: "{{ item.teams }}"
      loop_control:
        loop_var: team

      when:
        - item.teams is defined

  connection: local
  tags:
    - users
